### ISSUE TITLE
Planung AG-Treffen Juni

### ISSUE THREAD

**Issue by hennyu** [DH-RSE/AG#3]
Beim Mai-Orga-Treffen das nächste (große) AG-Treffen im Juni inhaltlich planen.

**Comment by tharman** [comment]
Unterschiede geisteswissenschaftlicher Forschungssoftware im Verglich zu anderer Software und Forschungssoftware wieder mit auf die Tagesordnung setzen?

**Comment by daniel-jettka** [comment]
Entwurf Agenda: https://github.com/DH-RSE/AG/wiki/2022-07-01-AG-DH-RSE-Meeting
